#!/bin/bash
# =============================================================
# EAGLES AI Platform - Azure AI Foundry MaaS Deployment
# No GPU quota needed. Uses Founders Hub credits.
# =============================================================
set -euo pipefail

echo "=== EAGLES AI Platform - Azure AI Foundry Serverless Setup ==="
echo ""

# ---- Prerequisites ----
echo "1. Checking Azure CLI + ML extension..."
az version --output table 2>/dev/null || { echo "ERROR: az CLI not installed"; exit 1; }
az extension add -n ml --yes 2>/dev/null || az extension update -n ml --yes 2>/dev/null
echo "   OK"
echo ""

# ---- Configuration ----
RESOURCE_GROUP="${RESOURCE_GROUP:-rg-eagles-ai-inference}"
LOCATION="${LOCATION:-eastus2}"
AI_HUB_NAME="${AI_HUB_NAME:-hub-eagles-ai}"
AI_PROJECT_NAME="${AI_PROJECT_NAME:-proj-eagles-inference}"

echo "2. Configuration:"
echo "   Resource Group:  $RESOURCE_GROUP"
echo "   Location:        $LOCATION"
echo "   AI Hub:          $AI_HUB_NAME"
echo "   AI Project:      $AI_PROJECT_NAME"
echo ""

# ---- Create Resource Group ----
echo "3. Creating resource group..."
az group create --name $RESOURCE_GROUP --location $LOCATION --output none
echo "   OK"

# ---- Create AI Hub ----
echo "4. Creating AI Hub (this may take 2-3 minutes)..."
az ml workspace create \
  --kind hub \
  --name $AI_HUB_NAME \
  --resource-group $RESOURCE_GROUP \
  --location $LOCATION \
  --output none 2>/dev/null || echo "   Hub may already exist, continuing..."
echo "   OK"

# ---- Create AI Project ----
echo "5. Creating AI Project..."
HUB_ID=$(az ml workspace show --name $AI_HUB_NAME --resource-group $RESOURCE_GROUP --query id -o tsv 2>/dev/null)
az ml workspace create \
  --kind project \
  --name $AI_PROJECT_NAME \
  --resource-group $RESOURCE_GROUP \
  --hub-id "$HUB_ID" \
  --output none 2>/dev/null || echo "   Project may already exist, continuing..."
echo "   OK"

# ---- Set defaults ----
az configure --defaults workspace=$AI_PROJECT_NAME group=$RESOURCE_GROUP location=$LOCATION

# ---- Deploy DeepSeek-R1 (sold directly by Azure, Founders Hub eligible) ----
echo ""
echo "6. Deploying DeepSeek-R1 serverless endpoint..."
cat > /tmp/deepseek-r1-endpoint.yml << 'YAML'
name: deepseek-r1-eagles
model_id: azureml://registries/azureml-deepseek/models/DeepSeek-R1
YAML
az ml serverless-endpoint create -f /tmp/deepseek-r1-endpoint.yml --output none 2>/dev/null && echo "   Deployed!" || echo "   May already exist or needs portal deployment"

# ---- Deploy DeepSeek-V3 (sold directly by Azure, Founders Hub eligible) ----
echo "7. Deploying DeepSeek-V3-0324 serverless endpoint..."
cat > /tmp/deepseek-v3-endpoint.yml << 'YAML'
name: deepseek-v3-eagles
model_id: azureml://registries/azureml-deepseek/models/DeepSeek-V3-0324
YAML
az ml serverless-endpoint create -f /tmp/deepseek-v3-endpoint.yml --output none 2>/dev/null && echo "   Deployed!" || echo "   May already exist or needs portal deployment"

# ---- Get endpoint URLs and keys ----
echo ""
echo "8. Retrieving endpoint credentials..."
echo ""

R1_URI=$(az ml serverless-endpoint show -n deepseek-r1-eagles --query scoring_uri -o tsv 2>/dev/null || echo "NOT_DEPLOYED")
R1_KEY=$(az ml serverless-endpoint get-credentials -n deepseek-r1-eagles --query primary_key -o tsv 2>/dev/null || echo "NOT_DEPLOYED")

V3_URI=$(az ml serverless-endpoint show -n deepseek-v3-eagles --query scoring_uri -o tsv 2>/dev/null || echo "NOT_DEPLOYED")
V3_KEY=$(az ml serverless-endpoint get-credentials -n deepseek-v3-eagles --query primary_key -o tsv 2>/dev/null || echo "NOT_DEPLOYED")

echo "   DeepSeek-R1:"
echo "     URI: $R1_URI"
echo "     Key: ${R1_KEY:0:10}..."
echo ""
echo "   DeepSeek-V3:"
echo "     URI: $V3_URI"
echo "     Key: ${V3_KEY:0:10}..."
echo ""

# ---- Generate .env file ----
echo "9. Generating .env file..."
cat > .env << ENVEOF
# Auto-generated by deploy-foundry.sh
LITELLM_MASTER_KEY=sk-eagles-$(openssl rand -hex 8 2>/dev/null || echo "local-$(date +%s)")

# Azure AI Foundry - DeepSeek-R1 (Founders Hub eligible)
DEEPSEEK_R1_API_KEY=$R1_KEY
DEEPSEEK_R1_API_BASE=$R1_URI

# Azure AI Foundry - DeepSeek-V3 (Founders Hub eligible)
DEEPSEEK_V3_API_KEY=$V3_KEY
DEEPSEEK_V3_API_BASE=$V3_URI

# Claude fallback (existing Max subscription)
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
ENVEOF
echo "   .env written"
echo ""

echo "=== Setup complete! ==="
echo ""
echo "Next steps:"
echo "  1. Review .env file and add ANTHROPIC_API_KEY if needed"
echo "  2. Run: docker compose up -d"
echo "  3. Run: bash test-gateway.sh"
echo "  4. Configure Claude Code:"
echo "     export ANTHROPIC_BASE_URL=http://localhost:4000"
echo "     export ANTHROPIC_AUTH_TOKEN=<your LITELLM_MASTER_KEY>"
