apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models
  namespace: ai-inference
  labels:
    app.kubernetes.io/part-of: eagles-ai-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi-premium
  resources:
    requests:
      storage: 256Gi
